--CREATE DATABASE TripService

--USE TripService

CREATE TABLE Cities
(
	Id INT IDENTITY PRIMARY KEY  NOT NULL,
	[Name] NVARCHAR(20) NOT NULL,
	CountryCode CHAR(2) NOT NULL
)

CREATE TABLE Hotels
(
	Id INT IDENTITY PRIMARY KEY  NOT NULL,
	[Name] NVARCHAR(30) NOT NULL,
	CityId INT NOT NULL REFERENCES Cities (Id),
	EmployeeCount INT NOT NULL,
	BaseRate DECIMAL (15,2)
)

CREATE TABLE Rooms
(
	Id INT IDENTITY PRIMARY KEY  NOT NULL,
	Price DECIMAL (15,2) NOT NULL,
	[Type] NVARCHAR(20) NOT NULL,
	Beds INT NOT NULL,
	HotelId INT  NOT NULL REFERENCES Hotels(Id)
)

CREATE TABLE Trips(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	RoomId INT REFERENCES Rooms(Id) NOT NULL,
	BookDate DATE NOT NULL,
	ArrivalDate DATE NOT NULL,
	ReturnDate DATE NOT NULL,
	CancelDate DATE,
	CHECK (BookDate < ArrivalDate),
	CHECK (ArrivalDate < ReturnDate)
)


CREATE TABLE Accounts
(
	Id INT IDENTITY PRIMARY KEY  NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	MiddleName NVARCHAR(20),
	LastName NVARCHAR(50) NOT NULL,
	CityId INT NOT NULL REFERENCES Cities(Id),
	BirthDate DATE NOT NULL,
	Email VARCHAR(100) UNIQUE NOT NULL 
)

CREATE TABLE AccountsTrips
(
	AccountId INT  NOT NULL REFERENCES Accounts(Id),
	TripId INT  NOT NULL REFERENCES Trips(Id),
	Luggage INT  NOT NULL CHECK(Luggage >= 0),
	PRIMARY KEY (AccountId, TripId)
)


