--CREATE DATABASE Movies

CREATE TABLE Directors
(
	Id INT PRIMARY KEY IDENTITY NOT NULL, 
	DirectorName VARCHAR(30) NOT NULL, 
	Notes VARCHAR(MAX)
)

CREATE TABLE Genres
(
	Id INT PRIMARY KEY IDENTITY NOT NULL, 
	GenreName VARCHAR(30) NOT NULL, 
	Notes VARCHAR(MAX)
)

CREATE TABLE Categories
(
	Id INT PRIMARY KEY IDENTITY NOT NULL, 
	CategoryName VARCHAR(30) NOT NULL, 
	Notes VARCHAR(MAX)
)

CREATE TABLE Movies
(
	Id INT PRIMARY KEY IDENTITY NOT NULL, 
	Title VARCHAR(50) NOT NULL, 
	DirectorId INT NOT NULL,
	CopyrightYear DATE NOT NULL,
	[Length] INT ,
	GenreId INT NOT NULL,
	CategoryId INT,
	Rating TINYINT,
	Notes VARCHAR(MAX)
)



INSERT INTO Directors (DirectorName,Notes) VALUES
('JOSH ...' , 'MNOGO E ZLE KATO DIRECTOR'),
('EDI KOI', 'MNOGO E ZLE KATO DIRECTOR'),
('NQKOI NOV' , 'MNOGO E ZLE KATO DIRECTOR'),
('LUCHAS' , 'MNOGO E ZLE KATO DIRECTOR'),
('Tarantino ' , 'Uma Thurman')

INSERT INTO Genres (GenreName,Notes) VALUES
('UJAS' , 'STRASHEN'),
('HORROR', 'MNOGO STRASHEN'),
('HORIBLE HORROR' , 'UJASNO STRASHEN'),
('Unknown' , 'MNOGO E ZLE'),
('BEST Genres' , 'MNOGO QK FILM')

INSERT INTO Categories (CategoryName,Notes) VALUES
('INTERESENI' , 'STRASHEN'),
('NE CHACK TOLKOVA INTERESENI', 'MNOGO STRASHEN'),
('STRASHENI' , 'UJASNO STRASHEN'),
('NE MNOGO IZVESTNI' , 'MNOGO E ZLE'),
('NEVEROQTNI' , 'MNOGO QK FILM')

INSERT INTO Movies (Title,DirectorId,CopyrightYear,[Length],GenreId,CategoryId,Rating,Notes) VALUES
('BASI FILMA' ,1, '2005-05-11' , 126,1,2 , NULL , 'STRASHEN'),
('NEW MOON' , 2,'2006-04-01' , 141,4,3 , NULL , NULL),
('OLD LADY' , 3,'2007-03-02' , 224,2,4 , NULL , NULL),
('NO NAME' , 4,'2008-02-02' , 24,3 ,1, NULL , NULL),
('KILL BILL' ,5, '2009-01-02' , 360,5,5 , NULL , 'STRASHEN')


ALTER TABLE Movies
ADD CONSTRAINT FK_DirectorName
FOREIGN KEY (DirectorId) REFERENCES Directors(Id);

ALTER TABLE Movies
ADD CONSTRAINT FK_GenreName
FOREIGN KEY (GenreId) REFERENCES Genres(Id);

ALTER TABLE Movies
ADD CONSTRAINT FK_CategoryName
FOREIGN KEY (CategoryId) REFERENCES Categories(Id);
SELECT * FROM Movies